version: 2.1
orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@3.2.0
workflows:
  test_my_app:
    jobs:
      - node/test:
          version: <node-version>
jobs:
  build:
    docker:
      - image: node:11.10.1

    

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      
      - run:
          name: install-npm
          command: cd ~ && pwd && npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - codecov/upload:
          file: './coverage/clover.xml'
     