# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@3.0.0
 
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs

jobs:
  build:
    docker:
      - image: node:11.10.1

    working_directory: ~/react-todo-list-app

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - node-cache-{{ checksum "package-lock.json" }}
        . 

      - node/install-packages:
          override-ci-command: npm install
          cache-path: ~/react-todo-list-app/node_modules 

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test
